name: dart_form_inputz
description: Form inputs for dart utilizing the "Formz" package.
version: 1.0.0
repository: https://github.com/mj12358/dart-form-inputz

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  formz: ^0.6.0

dev_dependencies:
  dart_lintz: ^1.2.0
  test: ^1.16.0
